### ISSUE TITLE
Notes to update "Submit your blueprint" docs

### ISSUE THREAD

**Issue by bph** [WordPress/blueprints#18]
1) add a note to https://github.com/adamziel/blueprints/blob/trunk/CONTRIBUTING.md

Once merged into trunk the path to blueprint folder is 
https://raw.githubusercontent.com/{community-blueprints-repo}/blueprints/trunk/{directory}/{filename.ext}
Example
https://raw.githubusercontent.com/adamziel/blueprints/**trunk**/custom-post/book.php

2) Meta description is not required for all blueprints, only for blueprints to be added to the gallery.

**Comment by adamziel** [comment]
The https://github.com/adamziel/blueprints/blob/trunk/CONTRIBUTING.md doc now covers both topics.
