### ISSUE TITLE
Add a "Edit in Blueprints Builder" link

### ISSUE THREAD

**Issue by adamziel** [WordPress/blueprints#33]
This Blueprints builder could be useful for editing and playing with Blueprints – let's add an "Edit in Builder" link to the gallery:

https://playground.wordpress.net/builder/builder.html

e.g. https://playground.wordpress.net/builder/builder.html#{%22landingPage%22:%22/wp-admin/%22,%22phpExtensionBundles%22:[%22kitchen-sink%22],%22preferredVersions%22:{%22php%22:%227.4%22,%22wp%22:%225.9%22},%22steps%22:[{%22step%22:%22login%22,%22username%22:%22admin%22,%22password%22:%22password%22}]}

Thinking about it more, it would be useful to support a `?blueprint-url=` query parameter in that builder.

**Comment by juanmaguitar** [comment]
I would also give more visibility to this [Blueprints Builder](https://playground.wordpress.net/builder/builder.html) in the docs. 

A good next step for this would be moving [this blueprints-builder section](https://github.com/adamziel/blueprints/blob/blueprints-crash-course/docs/troubleshoot-debug-blueprints.md#blueprints-builder) from `troubleshoot-debug-blueprints.md` to `README.md`

**Comment by juanmaguitar** [comment]
> Thinking about it more, it would be useful to support a ?blueprint-url= query parameter in that builder.

100% agree with this.

**Comment by ironnysh** [comment]
> I would also give more visibility to this Blueprints Builder in the docs. A good next step for this would be moving this blueprints-builder section from troubleshoot-debug-blueprints.md to README.md

How about adding it under [Ready to jump in?](https://github.com/adamziel/blueprints?tab=readme-ov-file#ready-to-jump-in), as a tool for prototyping Blueprints?

I'd still mention it as a resource in troubleshoot-debug-blueprints, though.

**Comment by juanmaguitar** [comment]
> How about adding it under Ready to jump in?, as a tool for prototyping Blueprints?

That would be a great place to highlight this tool sooner! 👍

**Comment by adamziel** [comment]
?blueprint-url support just landed: https://playground.wordpress.net/builder/builder.html?blueprint-url=https://raw.githubusercontent.com/adamziel/blueprints/trunk/blueprints/custom-post/blueprint.json

**Comment by adamziel** [comment]
I also just added the "Edit" link to the gallery: https://github.com/WordPress/blueprints/blob/trunk/GALLERY.md in https://github.com/WordPress/blueprints/commit/64abd2f20d050b1c7c2811445c469f3a788eefd1. I'll close this issue and let's discuss any formatting improvements in another one.
