### ISSUE TITLE
Q: branch vs folder? 

### ISSUE THREAD

**Issue by bph** [WordPress/blueprints#37]
In Contributing.md it says: 

_For example, if you want to load a content-export.xml file and your branch is called woocommerce-subscriptions, then your PR must contain a_
```
A blueprints/woocommerce-subscriptions/blueprint.json file
A blueprints/woocommerce-subscription/content-export.xml file the Blueprint should reference as follows:
{
	"steps": [
		{
			"step": "importWxr",
			"file": {
				"resource": "url",
				"url": "https://raw.githubusercontent.com/adamziel/blueprints/woocommerce-subscriptions/blueprints/woocommerce-subscriptions/content-export.xml"
			}
		}
	]
}
```
This makes it seem that the branch name and the folder name need to be the same. That doesn't seem to be necessarily the case. If i am correct I would suggest to change the example

That the example branch is called something different than the folder,  like /woo-subsriptions/
and the url: is modified to https://raw.githubusercontent.com/adamziel/blueprints/woo-subsriptions/blueprints/woocommerce-subscriptions/content-export.xml

And add another sentence in 
The folder of your files would be /woocommerce-subscription

It would read like this 

For example, if you want to load a `content-export.xml` file, 
you create a new folder in the blueprints directory, /woocommerce-subscription (the name should correpong to the name of the blueprint and  must hold two files. 
`A blueprints/woocommerce-subscriptions/blueprint.json file`
`A blueprints/woocommerce-subscription/content-export.xml file` 
Your branch you named /woo-subscription/ (this name is up to you) 

Then the Blueprint should reference as follows:
```{
	"steps": [
		{
			"step": "importWxr",
			"file": {
				"resource": "url",
				"url": "https://raw.githubusercontent.com/adamziel/blueprints/woo-subscriptions/blueprints/woocommerce-subscriptions/content-export.xml"
			}
		}
	]
}```

**Comment by adamziel** [comment]
> This makes it seem that the branch name and the folder name need to be the same. That doesn't seem to be necessarily the case. If i am correct I would suggest to change the example

You are correct Birgit, good spot 👍 the example could use brushing up.
