### ISSUE TITLE
404: "theme tester" Blueprint broken – WordPress theme unit testing data and accessibility data

### ISSUE THREAD

**Issue by adamziel** [WordPress/blueprints#38]
https://raw.githubusercontent.com/wpaccessibility/a11y-theme-unit-test/trunk/a11y-theme-unit-test-data.xml

https://raw.githubusercontent.com/WordPress/theme-test-data/trunk/themeunittestdata.wordpress.xml

![CleanShot 2024-04-22 at 15 33 09@2x](https://github.com/adamziel/blueprints/assets/205419/52a9e922-044d-4f44-9c3c-21992f531c8a)

cc @bph I wonder if it's intermittent or were they actually moved to another repo or directory

**Comment by adamziel** [comment]
Maybe we should have CI tests to confirm all the blueprints keep working

**Comment by bph** [comment]
Seems both repos don't have a /trunk default branch anymore. It works with /master 

https://raw.githubusercontent.com/WordPress/theme-test-data/master/themeunittestdata.wordpress.xml
https://raw.githubusercontent.com/wpaccessibility/a11y-theme-unit-test/master/a11y-theme-unit-test-data.xml
