### ISSUE TITLE
Contribution workflow: How to include additional files (e.g. plugin zip) in a PR?

### ISSUE THREAD

**Issue by adamziel** [WordPress/blueprints#6]
Contributing Guidelines say:

> All static files (WXR, ZIP, JPG etc.) referenced by the Blueprint must be included in the submitted directory in your Pull Request and referenced via the `raw.githubusercontent.com` domain.

However, it's unclear how to actually reference these files in blueprint.json in a PR. That blueprint can ship URLs pointing to the newly proposed branch, but once that branch is merged these URLs will need to magically start pointing to `trunk`.

Two solutions that came to mind:

1. CI job to rewrite the URLs. I don't like it, though. It's extra work and will make forking and adjusting these files more difficult.
2. Support URLs relative to the Blueprint. For example `{ "step": "installPlugin", "pluginZipFile": "./plugin.zip" }`. This would be a breaking change because relative URLs are now relative to the client site URL. Maybe that's fine, though? Or perhaps we could ship a new resource type, like "blueprint-relative-url"?

cc @bgrgicak @brandonpayton @dmsnell for ideas

**Comment by bgrgicak** [comment]
> This would be a breaking change because relative URLs are now relative to the client site URL. Maybe that's fine, though? Or perhaps we could ship a new resource type, like "blueprint-relative-url"?

This could be confusing, relative URLs are usually tied to the site context.
Using a new resource type would help, but it still feels like a workaround. 

What if blueprints accepted bas64 encoded data? This would remove the need for putting the data on a server. 
Playground could use a blueprint exporter and this could support storing data using base64.

**Comment by dmsnell** [comment]
The Playground could help some URLs by rewriting dynamically couldn't it? That is, recognize that it's a Github link, and if it's not the right `rawusercontent` domain then rewrite it?

**Comment by adamziel** [comment]
Related: https://github.com/adamziel/blueprints/issues/18

**Comment by adamziel** [comment]
I went for the CI job to rewrite branch URLs to trunk URLs:

https://github.com/adamziel/blueprints/commit/fabe4d22662c72a640fdaee737a0cafab2937d9c

Independently from that, I will explore @dmsnell's suggestion – it resolves another important problem.

**Comment by adamziel** [comment]
To resolve this issue, we'll need to document the expected URL for all assets is the https://raw.githubusercontent.com/ URL pointing to the proposed branch.

**Comment by adamziel** [comment]
Documented in [d2f9f8d](https://github.com/adamziel/blueprints/commit/d2f9f8d60ce861d1b610587e884de519f24c5b96)
