### ISSUE TITLE
Should we automatically delete PR branches after merge?

### ISSUE THREAD

**Issue by brandonpayton** [WordPress/blueprints#78]
When merging Playground PRs, the PR branch is auto-deleted, and I believe we also do this for other related repos. But we do not auto-delete merged PR branches in this repo.

Is there a reason for this, or should we enable this auto-delete feature for [WordPress/blueprints](https://github.com/WordPress/blueprints)?

I believe we're starting to accumulate branches from merged PRs.

cc @adamziel @bgrgicak

**Comment by brandonpayton** [comment]
Example: This PR is merged, but its branch lives on: https://github.com/WordPress/blueprints/pull/77

**Comment by bgrgicak** [comment]
@brandonpayton I assume that we need these branches for [the postprocess action ](https://github.com/WordPress/blueprints/blob/trunk/.github/workflows/postprocess.yml) to run. It sounds reasonable to delete the branch after this job runs successfully.

**Comment by adamziel** [comment]
Makes sense to me. How can this be enabled?

**Comment by adamziel** [comment]
I found and enabled this! I think the postprocess action will just work, but let's observe it.

[Image](https://github.com/user-attachments/assets/2b082890-a207-4f53-ac9d-f7147d184bc7)
 option:
