### ISSUE TITLE
Stylish Press stopped working

### ISSUE THREAD

**Issue by bgrgicak** [WordPress/blueprints#79]
The[ Stylish Press demo stopped working ](https://playground.wordpress.net/?blueprint-url=https%3A%2F%2Fraw.githubusercontent.com%2Fwordpress%2Fblueprints%2Ftrunk%2Fblueprints%2Fstylish-press%2Fblueprint.json). 

It could be related to the WP 6.7, because it works with 6.6: https://playground.wordpress.net/?wp=6.6&blueprint-url=https%3A%2F%2Fraw.githubusercontent.com%2Fwordpress%2Fblueprints%2Ftrunk%2Fblueprints%2Fstylish-press%2Fblueprint.json

Blueprint https://github.com/wordpress/blueprints/blob/trunk/blueprints/stylish-press/blueprint.json

**Comment by adamziel** [comment]
Thanks! I've just updated it to use WordPress 6.6. Not perfect, but it does the trick for as long as WP 6.6 is supported. I wonder if that's something about twentytwentyfive, I've seen others having similar issues:

![Image](https://github.com/user-attachments/assets/d2d78638-baed-472a-9ee1-5c51abd26026)

This also opens up an important question – should Blueprints default to the latest WordPress release?

**Comment by bgrgicak** [comment]
> This also opens up an important question – should Blueprints default to the latest WordPress release?

Using the latest version is expected behavior for me. What would you prefer?
